### ISSUE TITLE
Collection homepage throws errors / crashes

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#112]
Today, when using the latest `master` code, the Collection homepage errors out with:

```
Error in SSR, serving for direct CSR TypeError: Cannot read property 'find' of undefined
    at t.e.findMetadata (D:\programming\dspace-angular\dist\server\index.js:9:16802)
    at t.get [as introductoryText] (D:\programming\dspace-angular\dist\server\index.js:40:17559)
    at t.detectChangesInternal (D:\programming\dspace-angular\dist\server\index.js:39:2201)
    at t.e.detectChanges (D:\programming\dspace-angular\dist\server\index.js:1:26940)
    at e.detectChangesInNestedViews (D:\programming\dspace-angular\dist\server\index.js:2:17870)
    at t.detectChangesInternal (D:\programming\dspace-angular\dist\server\index.js:38:28949)
    at t.e.detectChanges (D:\programming\dspace-angular\dist\server\index.js:1:26940)
    at t.detectChangesInternal (D:\programming\dspace-angular\dist\server\index.js:38:27486)
    at t.e.detectChanges (D:\programming\dspace-angular\dist\server\index.js:1:26940)
    at e.detectChangesInNestedViews (D:\programming\dspace-angular\dist\server\index.js:2:17870)
    at t.detectChangesInternal (D:\programming\dspace-angular\dist\server\index.js:38:25243)
```
The error crashes the entire application.

I've also attempted a complete clean & rebuild (`yarn run clean & yarn run global & yarn install & yarn server`), but the error still persists.  Other pages (homepage and Item page) are unaffected.

**Comment by tdonohue** [comment]
Reproducing the error after starting in development mode (`yarn run watch:dev`) provides a more detailed error message:
```
Error in SSR, serving for direct CSR
EXCEPTION: Error in ./CollectionPageComponent class CollectionPageComponent - inline template:4:6 caused by: Cannot read property 'find' of undefined
ORIGINAL EXCEPTION: Cannot read property 'find' of undefined
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'find' of undefined
    at Collection.DSpaceObject.findMetadata (D:\programming\dspace-angular\dist\server\index.js:13943:13)
    at Collection.get [as introductoryText] (D:\programming\dspace-angular\dist\server\index.js:68153:25)
    at DebugAppView.View_CollectionPageComponent1.detectChangesInternal (/CollectionPageModule/CollectionPageComponent/component.ngfactory.js:187:166)    at DebugAppView.AppView.detectChanges (D:\programming\dspace-angular\dist\server\index.js:60188:14)
    at DebugAppView.detectChanges (D:\programming\dspace-angular\dist\server\index.js:60281:44)
    at ViewContainer.detectChangesInNestedViews (D:\programming\dspace-angular\dist\server\index.js:60373:37)
    at DebugAppView.View_CollectionPageComponent0.detectChangesInternal (/CollectionPageModule/CollectionPageComponent/component.ngfactory.js:50:14)
    at DebugAppView.AppView.detectChanges (D:\programming\dspace-angular\dist\server\index.js:60188:14)
    at DebugAppView.detectChanges (D:\programming\dspace-angular\dist\server\index.js:60281:44)
    at DebugAppView.View_CollectionPageComponent_Host0.detectChangesInternal (/CollectionPageModule/CollectionPageComponent/host.ngfactory.js:29:19)
```

**Comment by tdonohue** [comment]
This bug also seems to affect PR #108, when the Community homepage attempts to load Collection information.  Though when using that PR, the error is with loading the Collection "shortDescription":

```
Error in SSR, serving for direct CSR
EXCEPTION: Error in ./CommunityPageSubCollectionListComponent class CommunityPageSubCollectionListComponent - inline template:6:33 caused by: Cannot read property 'find' of undefined
ORIGINAL EXCEPTION: Cannot read property 'find' of undefined
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'find' of undefined
    at Collection.DSpaceObject.findMetadata (D:\programming\dspace-angular\dist\server\index.js:14016:13)
    at Collection.get [as shortDescription] (D:\programming\dspace-angular\dist\server\index.js:68110:25)
```
