### ISSUE TITLE
Cannot export Metadata (CSV) from Collection

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1132]
**Describe the bug**
Cannot export a Metadata CSV from a Collection while logged in as an Administrator

**To Reproduce**
1. Login as an Admin
2. Browse to a Collection containing one or more Items
3. In the Admin Sidebar, select "Export" -> "Metadata" and select the Collection
4. A Process kicks off, but it immediately fails with this error:
```
2021-04-27 22:01:47.957 ERROR metadata-export - 1 @ Failed to parse the arguments given to the script with name: metadata-export and args: [-i, http://localhost:4000/handle/123456789/1118, -f, 9d8334e9-25d3-4a67-9cea-3dffdef80144.csv]
2021-04-27 22:01:47.959 ERROR metadata-export - 1 @ org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -f
	at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:360)
	at org.apache.commons.cli.DefaultParser.handleShortAndLongOption(DefaultParser.java:497)
	at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:243)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
	at org.dspace.scripts.DSpaceRunnable.parse(DSpaceRunnable.java:85)
	at org.dspace.scripts.DSpaceRunnable.initialize(DSpaceRunnable.java:75)
	at org.dspace.app.rest.repository.ScriptRestRepository.runDSpaceScript(ScriptRestRepository.java:149)
	at org.dspace.app.rest.repository.ScriptRestRepository.startProcess(ScriptRestRepository.java:114)
	at org.dspace.app.rest.repository.ScriptRestRepository$$FastClassBySpringCGLIB$$952d0402.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at org.dspace.app.rest.repository.ScriptRestRepository$$EnhancerBySpringCGLIB$$a9f8c134.startProcess(<generated>)
	at org.dspace.app.rest.ScriptProcessesController.startProcess(ScriptProcessesController.java:70)
	at org.dspace.app.rest.ScriptProcessesController$$FastClassBySpringCGLIB$$7be45783.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at org.dspace.app.rest.ScriptProcessesController$$EnhancerBySpringCGLIB$$172a7457.startProcess(<generated>)
```

**Expected behavior**
Should obviously be able to export to a Metadata CSV

**Related work**
This appears to be related to https://github.com/DSpace/DSpace/pull/2924 (where the --file param was banned from REST, and replaced by a preselected value).  However, this used to work and has broken more recently.

**Comment by tdonohue** [comment]
@benbosman : I'm assigning this to you/your team for analysis, as I *suspect* it's actually a backend bug.  As noted above, it sounds related to https://github.com/DSpace/DSpace/pull/2924, which your team worked on.

**Comment by artlowel** [comment]
There are issues on the angular and the backend side here

One issue is that the -f option to pass the file name has been removed on the backend, but the UI still provides it. So we need to remove it 

But another is that while the script should works with handles and uuids, it only accepts handles. @benbosman will still add an estimate to address that.

The angular side can be fixed in **1 hour** 
Atmire would like to claim it

**Comment by tdonohue** [comment]
@artlowel : Thanks for digging here. You are welcome to begin Angular work (added you to assignment).  I'll also keep this assigned to @benbosman for his assessment on the REST API issues.

**Comment by benbosman** [comment]
The REST part to support the UUID and add an IT should be doable in **2 hours**

We can work on that part as well

**Comment by tdonohue** [comment]
Thanks @benbosman .  Since this is small, for simplicity, I'm going to add both REST & Angular into this one ticket.  So, bumping the estimate to 3 hours total and assigning both you and @artlowel
