### ISSUE TITLE
Cannot Import Metadata (CSV) as an Admin

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1133]
**Describe the bug**
Cannot import a Metadata CSV while logged in as an Administrator.  Seems like the same problem as reported in https://github.com/DSpace/dspace-angular/issues/1132

**To Reproduce**
1. Login as an Admin
2. Create a CSV to import (preferably something small. It could be one line starting with a "+" to test creating a metadata import Item)
3. In the Admin Sidebar, select "Import" -> "Metadata" and drag & drop your CSV
4. A Process kicks off, but it immediately fails with this error:
```
2021-04-27 22:12:06.662 ERROR metadata-import - 2 @ Failed to parse the arguments given to the script with name: metadata-import and args: [-e, dspacedemo+admin@gmail.com, -f, 10673-2.csv]
2021-04-27 22:12:06.663 ERROR metadata-import - 2 @ org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -e
	at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:360)
	at org.apache.commons.cli.DefaultParser.handleShortAndLongOption(DefaultParser.java:497)
	at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:243)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
	at org.dspace.scripts.DSpaceRunnable.parse(DSpaceRunnable.java:85)
	at org.dspace.scripts.DSpaceRunnable.initialize(DSpaceRunnable.java:75)
	at org.dspace.app.rest.repository.ScriptRestRepository.runDSpaceScript(ScriptRestRepository.java:149)
	at org.dspace.app.rest.repository.ScriptRestRepository.startProcess(ScriptRestRepository.java:114)
	at org.dspace.app.rest.repository.ScriptRestRepository$$FastClassBySpringCGLIB$$952d0402.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at org.dspace.app.rest.repository.ScriptRestRepository$$EnhancerBySpringCGLIB$$a9f8c134.startProcess(<generated>)
	at org.dspace.app.rest.ScriptProcessesController.startProcess(ScriptProcessesController.java:70)
	at org.dspace.app.rest.ScriptProcessesController$$FastClassBySpringCGLIB$$7be45783.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at org.dspace.app.rest.ScriptProcessesController$$EnhancerBySpringCGLIB$$172a7457.startProcess(<generated>)
```

**Expected behavior**
Obviously, Import of Metadata CSV should work.

**Related work**
This seems like a very similar problem to https://github.com/DSpace/dspace-angular/issues/1132 and can likely be tackled by the same person

**Comment by tdonohue** [comment]
@benbosman : Assigning this to you as well for your team to analyze & estimate.  As noted above, this sounds (to me) like a very similar problem as https://github.com/DSpace/dspace-angular/issues/1132, so they likely should be investigated/solved together.

**Comment by artlowel** [comment]
As with #1132 the issue is that the params on the backend have changed, but the UI wasn't updated. It will take **1 hour** to update them. There are no rest issues here

Atmire would like to claim this task

**Comment by tdonohue** [comment]
@artlowel : Thanks for figuring this out. Assigning back to you for your team to work on.
