### ISSUE TITLE
Unable to run production distribution server without node_modules

### ISSUE THREAD

**Issue by wwelling** [DSpace/dspace-angular#1410]
**Describe the bug**
For production deployment it is desirable to run distribution without node_modules. This is critical for containerization where as an image with node_modules is over 2GB and a little over 200MB without. Webpack node externals usually only provides benefits for libraries and not so much for servers. Bundling dependencies should reduce overall image size through additional tree-shaking and potential performance gains by reducing runtime requires.

**To Reproduce**
1. yarn install
2. yarn build:prod
3. rimraf node_modules
4. node dist/server

**Expected behavior**
Running distribution server should run as normal without node_modules directory.

**Related work**
N/A

**Comment by wwelling** [comment]
Here are the node_modules entry points required.
```
Entrypoint server = server.js
  [0] ./server.ts 9.38 KiB {0} [built]
  [1] ./node_modules/tslib/tslib.es6.js 10.5 KiB {0} [built]
  [2] ./node_modules/zone.js/dist/zone-node.js 117 KiB {0} [built]
  [4] external "fs" 42 bytes {0} [built]
  [7] ./node_modules/reflect-metadata/Reflect.js 50 KiB {0} [built]
  [8] ./node_modules/rxjs/_esm5/index.js 3.33 KiB {0} [built]
[111] ./node_modules/pem/lib/pem.js 40.3 KiB {0} [built]
[115] external "path" 42 bytes {0} [built]
[125] external "https" 42 bytes {0} [built]
[126] ./node_modules/morgan/index.js 10.5 KiB {0} [built]
[141] ./node_modules/express/index.js 224 bytes {0} [built]
[143] ./node_modules/body-parser/index.js 2.59 KiB {0} [built]
[261] ./node_modules/compression/index.js 5.84 KiB {0} [built]
[267] ./node_modules/@angular/core/fesm2015/core.js 1.22 MiB {0} [built]
[367] ./node_modules/@nguniversal/express-engine/fesm2015/tokens.js 868 bytes {0} [built]
    + 2073 hidden modules
```

**Comment by wwelling** [comment]
Here is the error

```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'core-js/es/reflect'
Require stack:
- ./dspace-angular/dist/server/main.js
- ./dspace-angular/dist/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.IeXC (./dspace-angular/dist/server/main.js:125352:18)
    at __webpack_require__ (./dspace-angular/dist/server/main.js:20:30)
    at Object.K011 (./dspace-angular/dist/server/main.js:130273:1)
    at __webpack_require__ (./dspace-angular/dist/server/main.js:20:30)
    at ./dspace-angular/dist/server/main.js:84:18
    at Object.<anonymous> (./dspace-angular/dist/server/main.js:87:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    './dspace-angular/dist/server/main.js',
    './Development/dspace-angular/dist/server.js'
  ]
}
```

**Comment by wwelling** [comment]
![image](https://user-images.githubusercontent.com/8352733/142411839-20a3d87d-26b0-45ba-b4b1-018c374db8d5.png)
