### ISSUE TITLE
de German not working

### ISSUE THREAD

**Issue by WolfgangT71** [DSpace/dspace-angular#1453]
**Describe the bug**
A clear and concise description of what the bug is. Include the version(s) of DSpace where you've seen this problem & what *web browser* you were using. Link to examples if they are public.
The Language German de is not working, not even at the demo in version 7.
All other languages are working, but not german.
Look at:
https://demo7.dspace.org/home
All the time falls back to english, perhaps even  the fallback.

**Comment by WolfgangT71** [comment]
even whan one sets de as default it is not working as it should it just writes the internal codes

like
```

menu.section.browse_global_communities_and_collections
menu.section.browse_global 
menu.section.statistics
```

**Comment by tdonohue** [comment]
I've verified this today locally. It appears there may be a syntax problem in the German language file (de.json5).  When I select Deutsch in the UI, I see this error in my DevTools console:
```
ERROR SyntaxError: JSON5: invalid character '\r' at 2185:179
    at syntaxError (C:\Users\donohue\programming\dspace-angular\dist\server\main.js:1:6724348)
    at invalidChar (C:\Users\donohue\programming\dspace-angular\dist\server\main.js:1:6723601)
    at Object.string (C:\Users\donohue\programming\dspace-angular\dist\server\main.js:1:6720414)
    at lex (C:\Users\donohue\programming\dspace-angular\dist\server\main.js:1:6714291)
    at Object.parse (C:\Users\donohue\programming\dspace-angular\dist\server\main.js:1:6714673)
    at Observable_Observable._subscribe (C:\Users\donohue\programming\dspace-angular\dist\server\main.js:1:8314641)
    at Observable_Observable._trySubscribe (C:\Users\donohue\programming\dspace-angular\dist\server\main.js:1:2445273)
    at Observable_Observable.subscribe (C:\Users\donohue\programming\dspace-angular\dist\server\main.js:1:2445055)
    at TakeSubscriber.shareReplayOperation (C:\Users\donohue\programming\dspace-angular\dist\server\main.js:1:4364834)
    at Observable_Observable.subscribe (C:\Users\donohue\programming\dspace-angular\dist\server\main.js:1:2444909) {
  lineNumber: 2185,
  columnNumber: 179
}
```

It appears there's a missing closing quote on that line of the `de.json5` file: https://github.com/DSpace/dspace-angular/blob/main/src/assets/i18n/de.json5#L2185

I'll create a small PR to fix this bug.
