### ISSUE TITLE
User Profile page is broken

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1494]
**Describe the bug**
On `main`, the User Profile page no longer works in Production mode.  Selecting it results in a blank page.  Chrome DevTools will display this error:
```
core.js:6210 ERROR Error: The @link() for groups on e models uses the resource type GROUP, but there is no service with an @dataService(GROUP) annotation in order to retrieve it
    at e.resolveLinkWithoutAttaching (main-es2015.0bb8b9187f20f000e24a.js:1:2893781)
    at e.resolveLink (main-es2015.0bb8b9187f20f000e24a.js:1:2894809)
    at main-es2015.0bb8b9187f20f000e24a.js:1:2893584
    at Array.forEach (<anonymous>)
    at e.resolveLinks (main-es2015.0bb8b9187f20f000e24a.js:1:2893567)
    at c.project (main-es2015.0bb8b9187f20f000e24a.js:1:579256)
    at c._next (main-es2015.0bb8b9187f20f000e24a.js:1:2029028)
    at c.next (main-es2015.0bb8b9187f20f000e24a.js:1:557180)
    at c.notifyNext (main-es2015.0bb8b9187f20f000e24a.js:1:2029569)
    at o._next (main-es2015.0bb8b9187f20f000e24a.js:1:3243173)
```

**To Reproduce**
1. Visit demo7.dspace.org & login as any user
2. Click on the Profile link.

**Comment by tdonohue** [comment]
@artlowel : Could you or your team look at this early next week, if possible?
