### ISSUE TITLE
Home page recent submissions potentially retrieves new collections and communities

### ISSUE THREAD

**Issue by amgciadev** [DSpace/dspace-angular#2071]
**Describe the bug**
When testing in an new repository with just 1 item, with the recent submissions in home page enabled, objects other than items are also retrieved in the search and this causes for an error that prevents the submissions from loading

**To Reproduce**
1. It can only be reproduced with very small number of items (less that the page configured)
2. Access home page and an error prevents the submissions from loading

Error:

> 0|dspace-ui  | ERROR Error: followLink('thumbnail') was used as a required link for a Collection, but there is no property on Collection models with an @link() for thumbnail
0|dspace-ui  |     at LinkService.resolveLinkWithoutAttaching (/home/dspace/apollo-frontend/dist/server/main.js:1:1136693)
0|dspace-ui  |     at LinkService.resolveLink (/home/dspace/apollo-frontend/dist/server/main.js:1:1137020)
0|dspace-ui  |     at /home/dspace/apollo-frontend/dist/server/main.js:1:1135145
0|dspace-ui  |     at Array.forEach (<anonymous>)
0|dspace-ui  |     at LinkService.resolveLinks (/home/dspace/apollo-frontend/dist/server/main.js:1:1135117)
0|dspace-ui  |     at /home/dspace/apollo-frontend/dist/server/main.js:1:1141119
0|dspace-ui  |     at /home/dspace/apollo-frontend/dist/server/main.js:1:7051744
0|dspace-ui  |     at OperatorSubscriber2._this._next (/home/dspace/apollo-frontend/dist/server/main.js:1:6973339)
0|dspace-ui  |     at OperatorSubscriber2.Subscriber2.next (/home/dspace/apollo-frontend/dist/server/main.js:1:6924302)
0|dspace-ui  |     at /home/dspace/apollo-frontend/dist/server/main.js:1:7051893

**Expected behavior**
Only items are retrieved when searching

**Related work**
Link to any related tickets or PRs here.

**Comment by amgciadev** [comment]
This can be fixed by configuring the search call here: https://github.com/DSpace/dspace-angular/blob/485bb840ce7f8cb6e92537de4fba1b2f9e84de6d/src/app/home-page/recent-item-list/recent-item-list.component.ts#L68 to only retrieve Items (dsoTypes: [DSpaceObjectType.ITEM],).

Once this bug is confirmed I can try a simple pull request :)
