### ISSUE TITLE
Warning [ERR_HTTP_HEADERS_SENT]: Tried to set headers after they were sent to the client

### ISSUE THREAD

**Issue by uofmsean** [DSpace/dspace-angular#2315]
**Describe the bug**
Seeing more of the following messages in PM2 logs after upgrading to DSpace 7.5 in production:

```
Warning [ERR_HTTP_HEADERS_SENT]: Tried to set headers after they were sent to the client
```

System:

- DSpace 7.5
- Red Hat Enterprise Linux Server release 7.9 (Maipo)
- Node v16.18.1
- PM2 5.3.0
- Java openjdk version "11.0.19" 2023-04-18 LTS

PM2 mspace-ui.json to start 4 Node processes:

```
           "instances": "4",
           "exec_mode": "cluster",
           "node_args": [
              "--max-old-space-size=1500"
           ],
           "env": {
              "NODE_ENV": "production"
           }
```

**To Reproduce**
Hard to pinpoint at the moment since there is no other context in the log files. Increased message count in production (compared to development) due to increased number of users and load. Will probably require debug logging to narrow it down. 

**Expected behavior**
Avoid header modifications after res.send() or res.end() for example.

**Related work**
N/A

**Comment by tdonohue** [comment]
@uofmsean : I think this error is thrown in the DSpace code here: https://github.com/DSpace/dspace-angular/blob/main/server.ts#L277-L281

Basically, there are some scenarios where Angular Universal (which does server-side rendering to pre-generate HTML) will *fail* with the `ERR_HTTP_HEADERS_SENT` error code.  They are not all possible for us to fix if the issue is in Angular itself...so, we'd need to narrow down what error is occurring to see if we can fix it in DSpace.

If you'd like to debug the issue you are seeing though, you should change that `console.warn` to show the details of the error.  Not sure if they'd be useful but they may provide some clues at least.  Something like this:
```
console.warn('Warning [ERR_HTTP_HEADERS_SENT]: Tried to set headers after they were sent to the client', err);
```

Overall, we'd need to find a way to reliably reproduce the error in order to find a fix.

**Comment by uofmsean** [comment]
Thanks @tdonohue. I'll take your advice and see if I can find what is causing it.

**Comment by danielcoelhocgu** [comment]
I am seeing this error message in our DSpace 9.0 instance when accessing permanent URIs (such as `/handle/XXX/YYY`).

```
Redirecting from /handle/1/4 to /communities/780e9910-3f1d-4440-9280-84c57f265595 with 301
GET /handle/1/4 301 506.669 ms - 90
Warning [ERR_HTTP_HEADERS_SENT]: Tried to set headers after they were sent to the client Error: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (node:_http_outgoing:699:11)
    at ServerResponse.res.set.res.header (/opt/dspace/dist/server/main.js:1:2948419)
    at ServerResponse.res.send (/opt/dspace/dist/server/main.js:1:2942787)
    at /opt/dspace/dist/server/main.js:1:8167245
    at _ZoneDelegate.invoke (/opt/dspace/dist/server/main.js:1:4147583)
    at ZoneImpl2.run (/opt/dspace/dist/server/main.js:1:4140156)
    at /opt/dspace/dist/server/main.js:1:4158491
    at _ZoneDelegate.invokeTask (/opt/dspace/dist/server/main.js:1:4148425)
    at ZoneImpl2.runTask (/opt/dspace/dist/server/main.js:1:4141225)
    at drainMicroTaskQueue (/opt/dspace/dist/server/main.js:1:4151659) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
Error: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (node:_http_outgoing:699:11)
    at ServerResponse.res.set.res.header (/opt/dspace/dist/server/main.js:1:2948419)
    at ServerResponse.res.send (/opt/dspace/dist/server/main.js:1:2942787)
GET /communities/780e9910-3f1d-4440-9280-84c57f265595 - - ms - -
    at /opt/dspace/dist/server/main.js:1:8167245
    at _ZoneDelegate.invoke (/opt/dspace/dist/server/main.js:1:4147583)
    at ZoneImpl2.run (/opt/dspace/dist/server/main.js:1:4140156)
    at /opt/dspace/dist/server/main.js:1:4158491
    at _ZoneDelegate.invokeTask (/opt/dspace/dist/server/main.js:1:4148425)
    at ZoneImpl2.runTask (/opt/dspace/dist/server/main.js:1:4141225)
    at drainMicroTaskQueue (/opt/dspace/dist/server/main.js:1:4151659)
```

From what I could debug, the problem happens when SSR is active. When DSpace issues a 301 redirect, it tries to render the target URL and send the new page in the same request, thus triggering the error.

Our instance runs behind an AWS Load Balancer, which does not like the new headers and shows a 502 error to the client.

To fix this, I added this check before line 272 in `server.ts` (https://github.com/DSpace/dspace-angular/blob/bcc437d029d81480c37153b2790b71f93e70ca6b/server.ts#L272)

```js
if (res.headersSent) {
  return;
}
```

This prevents the application to send another content if headers were already sent. I am not sure if this is the best solution, but it fixed my problem and I have not observed any side effects so far.

**Comment by tdonohue** [comment]
@danielcoelhocgu : If that workaround continues to work well for you, please consider sending us a PR to update DSpace in the same way.  DSpace is built/maintained entirely by volunteers.  Sometimes creating a PR can help encourage others to try out the fix and report back on what they find as well (including if they discover side effects).

**Comment by pkmcnc** [comment]
> To fix this, I added this check before line 272 in `server.ts` (

Seems to work for me. DSpace 9.1

**Comment by quintusdias** [comment]
Ditto for me, DSpace 9.1.

**Comment by divinoirj** [comment]
This works for me. DSpace 8.2

**Comment by nwoodward** [comment]
This change reduced the number of "Warning [ERR_HTTP_HEADERS_SENT]: Tried to set headers after they were sent to the client" warnings in the PM2 logs to zero for us on DSpace 8.2. This is nice because on our larger repositories there will be several thousand of these warnings per day that fill up the PM2 logs.

**Comment by pkmcnc** [comment]
Based on my logs cases of ERR_HTTP_HEADERS_SENT became scarce with the suggested fix. 
Although still there, they are hardly a problem
Just compare

zgrep -c "ERR_HTTP_HEADERS_SENT" ~/.pm2/logs/*

before:
dspace-ui-error-6__2025-08-15_00-00-00.log.gz:877
dspace-ui-error-6__2025-08-19_00-00-00.log.gz:1004
dspace-ui-error-7__2025-08-15_00-00-00.log.gz:860
dspace-ui-error-8__2025-08-15_00-00-00.log.gz:853
dspace-ui-error-9__2025-08-15_00-00-00.log.gz:860

vs now:
dspace-ui-error-4__2025-09-21_00-00-00.log.gz:10
dspace-ui-error-4__2025-09-22_00-00-00.log.gz:12
dspace-ui-error-4__2025-09-22_19-25-33.log.gz:15
dspace-ui-error-4__2025-09-23_00-00-00.log.gz:5
dspace-ui-error-4__2025-09-24_00-00-00.log.gz:46
