### ISSUE TITLE
Approve item operation in Workflow tasks fails

### ISSUE THREAD

**Issue by Ramzi04** [DSpace/dspace-angular#2410]
**Describe the bug**
Version: 7.6.0-next
After I submit an item, I claimed successfully the item. But when I try to approve it, it shows the following error:

**To Reproduce**
1. Submit an item
2. Go to workflow tasks
3. Approve the submitted item.

**Expected behavior**
I expect that when I click on Approve button, it shows a successful message.
<img width="475" alt="Screenshot from 2023-08-02 14-45-49" src="https://github.com/DSpace/dspace-angular/assets/22014761/3def34ee-1cba-4e9c-ac2e-bff72d93441f">

**Comment by tdonohue** [comment]
@Ramzi04 : Could you please follow our Troubleshooting guide to check to see what the underlying error is?  https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace7.x(orabove)

We need to see the underlying error in order to diagnose the problem.  It could be possible that this is a simple configuration issue (with your site), but it also could be a bug.  We'd need the underlying error to be sure.

**Comment by Ramzi04** [comment]
**The Dspace environement:**
  DSpace version:  7.6-SNAPSHOT
  SCM revision:  ${buildNumber}
  SCM branch:  UNKNOWN_BRANCH
  OS:  Linux(amd64) version 5.19.0-41-generic
  Applications:
      Discovery:  enabled.
      JRE:  Ubuntu version 11.0.18
      Ant version:  Apache Ant(TM) version 1.10.12 compiled on January 17 1970
      Maven version:  3.6.3
   DSpace home:  /dspace

**Error Message in the User Interface** 
<img width="475" alt="Screenshot from 2023-08-08 17-06-34" src="https://github.com/DSpace/dspace-angular/assets/22014761/3043389b-acea-4c7b-bfb5-f6b3595165a5">
![Screenshot from 2023-08-08 17-08-58](https://github.com/DSpace/dspace-angular/assets/22014761/a4639937-906e-4514-b147-fdcc1189a66c)

**Error messages in the REST API logs**

localhost_access_log:
```
/server/api/core/items/a383d25c-e5e5-484c-a806-dde3243c3eeb/bundles HTTP/1.1" 200 5
10.1.0.150 - - [08/Aug/2023:17:04:19 +0300] "GET /server/api/workflow/workflowitems/31/submitter HTTP/1.1" 204 -
10.1.0.150 - - [08/Aug/2023:17:04:20 +0300] "GET /server/api/core/items/a383d25c-e5e5-484c-a806-dde3243c3eeb/bundles HTTP/1.1" 200 2231
10.1.0.150 - - [08/Aug/2023:17:04:20 +0300] "GET /server/api/core/items/da1acb61-f4c7-4a6a-9883-70a2eabcb6ff/bundles HTTP/1.1" 200 2231
10.1.0.150 - - [08/Aug/2023:17:05:26 +0300] "OPTIONS /server/api/workflow/claimedtasks/12 HTTP/1.1" 200 5
10.1.0.150 - - [08/Aug/2023:17:05:28 +0300] "POST /server/api/workflow/claimedtasks/12 HTTP/1.1" 422 5
```
catalina.out:
```
[2023-08-08 16:58:00] [info] Initializing ProtocolHandler ["http-nio-8080"]
[2023-08-08 16:58:00] [info] Initializing ProtocolHandler ["http-nio--1"]
[2023-08-08 16:58:00] [crit] Failed to initialize component [Connector[HTTP/1.1-auto-1]]
[2023-08-08 16:58:00] [crit] org.apache.catalina.LifecycleException: Protocol handler initialization failed
[2023-08-08 16:58:00] [crit]     at org.apache.catalina.connector.Connector.initInternal(Connector.java:1049)
[2023-08-08 16:58:00] [crit]     at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
[2023-08-08 16:58:00] [crit]     at org.apache.catalina.core.StandardService.initInternal(StandardService.java:556)
[2023-08-08 16:58:00] [crit]     at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
[2023-08-08 16:58:00] [crit]     at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:1042)
[2023-08-08 16:58:00] [crit]     at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
[2023-08-08 16:58:00] [crit]     at org.apache.catalina.startup.Catalina.load(Catalina.java:724)
[2023-08-08 16:58:00] [crit]     at org.apache.catalina.startup.Catalina.load(Catalina.java:746)
[2023-08-08 16:58:00] [crit]     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2023-08-08 16:58:00] [crit]     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2023-08-08 16:58:00] [crit]     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2023-08-08 16:58:00] [crit]     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2023-08-08 16:58:00] [crit]     at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:305)
[2023-08-08 16:58:00] [crit]     at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:475)
[2023-08-08 16:58:00] [crit] Caused by: java.lang.IllegalArgumentException: port out of range:-1
[2023-08-08 16:58:00] [crit]     at java.base/java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143)
[2023-08-08 16:58:00] [crit]     at java.base/java.net.InetSocketAddress.<init>(InetSocketAddress.java:188)
[2023-08-08 16:58:00] [crit]     at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:272)
[2023-08-08 16:58:00] [crit]     at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:228)
[2023-08-08 16:58:00] [crit]     at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1213)
[2023-08-08 16:58:00] [crit]     at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1226)
[2023-08-08 16:58:00] [crit]     at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:603)
[2023-08-08 16:58:00] [crit]     at org.apache.coyote.http11.AbstractHttp11Protocol.init(AbstractHttp11Protocol.java:80)
[2023-08-08 16:58:00] [crit]     at org.apache.catalina.connector.Connector.initInternal(Connector.java:1046)
[2023-08-08 16:58:00] [crit]     ... 13 more
[2023-08-08 16:58:00] [info] Server initialization in [1230] milliseconds
```

dspace.log:

```
2023-08-08 17:05:28,009 ERROR 12362d7e-c0e5-4943-991c-b96a71bc9835 609eb838-9f53-487d-9db7-bd885b66f03e org.dspace.app.rest.RestResourceController @ Invalid workflow action: Invalid step outcome
org.dspace.app.rest.exception.UnprocessableEntityException: Invalid workflow action: Invalid step outcome
	at org.dspace.app.rest.repository.ClaimedTaskRestRepository.action(ClaimedTaskRestRepository.java:224) ~[classes/:7.6-SNAPSHOT]
	at org.dspace.app.rest.repository.ClaimedTaskRestRepository.action(ClaimedTaskRestRepository.java:67) ~[classes/:7.6-SNAPSHOT]
	at org.dspace.app.rest.repository.DSpaceRestRepository.action(DSpaceRestRepository.java:484) ~[classes/:7.6-SNAPSHOT]
	at org.dspace.app.rest.repository.DSpaceRestRepository$$FastClassBySpringCGLIB$$615525f9.invoke(<generated>) ~[classes/:7.6-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.dspace.app.rest.repository.ClaimedTaskRestRepository$$EnhancerBySpringCGLIB$$268ed6d.action(<generated>) ~[classes/:7.6-SNAPSHOT]
	at org.dspace.app.rest.RestResourceController.action(RestResourceController.java:501) [classes/:7.6-SNAPSHOT]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) [spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) [spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) [spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) [spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072) [spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965) [spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) [spring-webmvc-5.3.27.jar:5.3.27]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) [tomcat9-servlet-api-9.0.58.jar:?]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.3.27.jar:5.3.27]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [tomcat9-servlet-api-9.0.58.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat9-websocket-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.springframework.web.filter.AbstractRequestLoggingFilter.doFilterInternal(AbstractRequestLoggingFilter.java:289) [spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.27.jar:5.3.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.dspace.app.rest.filter.DSpaceRequestContextFilter.doFilter(DSpaceRequestContextFilter.java:45) [classes/:7.6-SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.dspace.app.rest.filter.ContentLanguageHeaderResponseFilter.doFilter(ContentLanguageHeaderResponseFilter.java:51) [classes/:7.6-SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.dspace.utils.servlet.DSpaceWebappServletFilter.doFilter(DSpaceWebappServletFilter.java:84) [dspace-services-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:337) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.8.jar:5.7.8]
	at org.dspace.app.rest.security.AnonymousAdditionalAuthorizationFilter.doFilterInternal(AnonymousAdditionalAuthorizationFilter.java:67) [classes/:7.6-SNAPSHOT]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.27.jar:5.3.27]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:223) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:223) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:223) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:223) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.8.jar:5.7.8]
	at org.dspace.app.rest.security.StatelessAuthenticationFilter.doFilterInternal(StatelessAuthenticationFilter.java:102) [classes/:7.6-SNAPSHOT]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.27.jar:5.3.27]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:132) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.27.jar:5.3.27]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) [spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.27.jar:5.3.27]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.27.jar:5.3.27]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.27.jar:5.3.27]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.27.jar:5.3.27]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186) [spring-security-web-5.7.8.jar:5.7.8]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) [spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) [spring-web-5.3.27.jar:5.3.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.27.jar:5.3.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) [spring-boot-actuator-2.7.12.jar:2.7.12]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.27.jar:5.3.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:126) [spring-boot-2.7.12.jar:2.7.12]
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:64) [spring-boot-2.7.12.jar:2.7.12]
	at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:101) [spring-boot-2.7.12.jar:2.7.12]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.27.jar:5.3.27]
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:119) [spring-boot-2.7.12.jar:2.7.12]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) [spring-web-5.3.27.jar:5.3.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102) [spring-web-5.3.27.jar:5.3.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.20.0.jar:2.20.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359) [tomcat9-catalina-9.0.58.jar:9.0.58]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) [tomcat9-coyote-9.0.58.jar:9.0.58]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat9-coyote-9.0.58.jar:9.0.58]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) [tomcat9-coyote-9.0.58.jar:9.0.58]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735) [tomcat9-coyote-9.0.58.jar:9.0.58]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat9-coyote-9.0.58.jar:9.0.58]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat9-util-9.0.58.jar:9.0.58]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat9-util-9.0.58.jar:9.0.58]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat9-util-9.0.58.jar:9.0.58]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.dspace.workflow.WorkflowException: Invalid step outcome
	at org.dspace.xmlworkflow.XmlWorkflowServiceImpl.processOutcome(XmlWorkflowServiceImpl.java:513) ~[dspace-api-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
	at org.dspace.xmlworkflow.XmlWorkflowServiceImpl.doState(XmlWorkflowServiceImpl.java:389) ~[dspace-api-7.6-SNAPSHOT.jar:7.6-SNAPSHOT]
	at org.dspace.app.rest.repository.ClaimedTaskRestRepository.action(ClaimedTaskRestRepository.java:214) ~[classes/:7.6-SNAPSHOT]
	... 148 more

```

**Comment by Ramzi04** [comment]
Hi folks. Any good news !

**Comment by tdonohue** [comment]
@Ramzi04 : I'm not able to reproduce this issue locally or on our demo site at https://demo.dspace.org/

That implies to me that it may be a misconfiguration on your end, or maybe your installation or upgrade (if this was an upgraded site) didn't go smoothly?

The error itself seems to say your workflow.xml is misconfigured:
```
org.dspace.app.rest.exception.UnprocessableEntityException: Invalid workflow action: Invalid step outcome
```

That error seems to imply you have an invalid value in one of the "outcomes" of a step:
https://github.com/DSpace/DSpace/blob/main/dspace/config/spring/api/workflow.xml#L41-L46

Maybe you accidentally modified this file and need to revert the changes?  Or maybe this was an upgrade from DSpace 6, and you failed to update your database properly by running "./dspace database migrate ignored"?   It's difficult to say, but this appears to be an issue on your end. It's not in the DSpace codebase as far as I can tell.
