### ISSUE TITLE
Submission form is cutoff / overlaps with side menu (in pre-7.6.1 only)

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#2557]
**Describe the bug**
On latest `main` and `dspace-7_x`, the Submission form is cuttoff / overlaps with the sidebar menu.  It appears to be a side effect of #2454 , as reverting those changes fixes the problem (when I try that locally)

See this screenshot
![cutoff-submissionform](https://github.com/DSpace/dspace-angular/assets/483997/cb74e40c-79b2-4b71-b7dd-327292e1f381)

**To Reproduce**
1. Can be reproduced on https://demo.dspace.org and https://sandbox.dspace.org (or locally via the latest code.
2. Login and go to the Submission Form

**Related work**
Caused by #2454

**Comment by tdonohue** [comment]
Solving this issue may require reverting #2454, unless a better fix can be found.  Pinging you @floriangantner just in case you have time to help investigate.

**Comment by tdonohue** [comment]
Errors that appear in Console on (seemingly) every page click (when running in production mode: `yarn build:prod; yarn serve:ssr`): 
```
ERROR Error: NG03402
    at Le (main.dcd17e51f7449cc8.js:1:1377219)
    at Io.reportError (main.dcd17e51f7449cc8.js:1:1377253)
    at Io._flushAnimations (main.dcd17e51f7449cc8.js:1:1379925)
    at Io.flush (main.dcd17e51f7449cc8.js:1:1376684)
    at ge.flush (main.dcd17e51f7449cc8.js:1:1388266)
    at main.dcd17e51f7449cc8.js:1:1396292
    at Z.invoke (polyfills.2583206b8351234c.js:1:17141)
    at Kt.run (polyfills.2583206b8351234c.js:1:12406)
    at Va.runOutsideAngular (main.dcd17e51f7449cc8.js:1:2126778)
    at ge.end (main.dcd17e51f7449cc8.js:1:1396231)
```

I think we may need to revert #2454... it seems to have some unexpected side effects over the entire site. (These errors do NOT occur on every page click when #2454 is reverted)

**Comment by tdonohue** [comment]
Fixed by reverting #2454
