### ISSUE TITLE
The "custom" theme no longer works

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#2977]
**Describe the bug**
Originally discovered while testing #2865 , however it's also reproducible on `main`.

If you attempt to run the DSpace UI with the "custom" theme. a lot of features will no longer work.  Here's what the homepage looks like:

![custom-theme](https://github.com/DSpace/dspace-angular/assets/483997/bb464237-9e40-43e4-b602-e270c4d03a11)

**To Reproduce**
1. Enable custom theme:
    ```
    themes:
      - name: custom
    ```
2. Start UI in production mode:  `yarn build:prod; yarn serve:ssr`
3. Access the homepage and it will look like above. The header no longer works, no ability to login or browse the site, much of the homepage content no longer displays, etc. Individual item pages are no better.
4. Some SSR errors will also be thrown that look like this:
    ```
    ERROR TypeError: Cannot read properties of undefined (reading 'onDestroy')
    at Object.ɵɵpipe (C:\dspace-angular\dist\server\main.js:1:4326830)
    at template (C:\dspace-angular\dist\server\1210.js:1:3854)
    at executeTemplate (C:\dspace-angular\dist\server\main.js:1:4182823)
    at renderView (C:\dspace-angular\dist\server\main.js:1:4198373)
    at renderComponent (C:\dspace-angular\dist\server\main.js:1:4198106)
    at renderChildComponents (C:\dspace-angular\dist\server\main.js:1:4198794)
    at renderView (C:\dspace-angular\dist\server\main.js:1:4198836)
    at ComponentFactory.create (C:\dspace-angular\dist\server\main.js:1:4235830)
    at R3ViewContainerRef.createComponent (C:\dspace-angular\dist\server\main.js:1:4239623)
    at Object.next (C:\dspace-angular\dist\server\main.js:1:2265629)
    ```

**Expected behavior**
Obviously the `custom` theme should still work.

**Related work**
It's unclear to me when this issue began.  It might be a side effect of recent Angular upgrades (#2871 or #2934 ) or something else entirely.

**Comment by artlowel** [comment]
@tdonohue we can work on this

**Comment by ybnd** [comment]
For future reference: @artlowel and I discussed whether we could make another custom ESLint rule to check for this sort of thing in the future:
- overall it should be doable to force import/provider lists to stay in sync, but a bit more complex than the rules in #2865
- however, themed versions of components may also introduce new components/directives/... or _remove_ some of the ones that were used in the unthemed component
- we'd need to tell which imports/providers are actually _used_ in the themed component

AFAIK this is something that should be checked during compilation, and that's how it used to work before.
