### ISSUE TITLE
SSR error appears on each page: `TypeError: Cannot read properties of undefined (reading 'userAgent')`

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#3000]
**Describe the bug**
After merging #2976, any time you run the UI in production mode, the following Server-side rendering error occurs:
```
ERROR TypeError: Cannot read properties of undefined (reading 'userAgent')
    at RootComponent2.getBrowserName (C:\dspace-angular\dist\server\main.js:1:1008203)
    at RootComponent2.ngOnInit (C:\dspace-angular\dist\server\main.js:1:1006659)
    at callHookInternal (C:\dspace-angular\dist\server\main.js:1:4136369)
    at callHook (C:\dspace-angular\dist\server\main.js:1:4136729)
    at callHooks (C:\dspace-angular\dist\server\main.js:1:4136119)
    at executeInitAndCheckHooks (C:\dspace-angular\dist\server\main.js:1:4135456)
    at refreshView (C:\dspace-angular\dist\server\main.js:1:4207799)
    at detectChangesInView$1 (C:\dspace-angular\dist\server\main.js:1:4211075)
    at detectChangesInViewIfAttached (C:\dspace-angular\dist\server\main.js:1:4210634)
    at detectChangesInEmbeddedViews (C:\dspace-angular\dist\server\main.js:1:4210339)
```

The issue appears to be on this line: https://github.com/DSpace/dspace-angular/blob/main/src/app/root/root.component.ts#L147

**To Reproduce**
1. Start the UI in production mode: `yarn install; yarn build:prod; yarn serve:ssr`
2. Access the homepage (or any page).  In the console where you ran `yarn serve:ssr`, you'll see the above TypeError.

**Comment by tdonohue** [comment]
@davide-negretti : This is a bug that is caused by #2976.  It's likely a simple fix.  If you have time to work on a PR, I'd appreciate it.

**Comment by tdonohue** [comment]
Nevermind, I figured out the fix myself.  It was simple after all.  See #3004
