### ISSUE TITLE
Fresh Install on Windows throws response errors

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#77]
Environment:
* Windows 10
* Node 6.10.1
* NPM 3.10.10
* Yarn 0.21.3

Steps to reproduce:
* clone repo
* `yarn run global`
* `yarn install`
* `yarn start` (or `yarn watch`)
* Attempt to access http://localhost:3000 in browser

Th result is that the server immediately dies (browser displays "The connection was reset." error and nothing is displayed). Also, the following error occurs:
```
Listening on: http://:::3000
Error in SSR, serving for direct CSR e {
  _body:
   { Error: read ECONNRESET
       at exports._errnoException (util.js:1018:11)
       at TCP.onread (net.js:572:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' },
  status: 200,
  ok: true,
  statusText: 'Ok',
  headers: t { _headers: Map {}, _normalizedNames: Map {} },
  type: 3,
  url: null }
EXCEPTION: Response with status: 200 Ok for URL: null

D:\programming\dspace-angular\node_modules\zone.js\dist\zone-node.js:158
                        throw error;
                        ^
Response with status: 200 Ok for URL: null
error Command failed with exit code 1.
```

This error seems to be the one noted here: https://github.com/ngx-translate/core/issues/362

In that ticket, the suggestion is the move `UniversalModule` to load *before* `TranslateModule`. 

I tried doing that in both our `node.module.ts` and `browser.module.ts`. This resolves the previously mentioned error, and results in the homepage loading successfully.  However, on the backend, I now see a new error:

```
EXCEPTION: This method is not implemented in Parse5DomAdapter: getCookie
ORIGINAL STACKTRACE:
Error: This method is not implemented in Parse5DomAdapter: getCookie
    at r (D:\programming\dspace-angular\dist\server\index.js:32:15014)
    at e.getCookie (D:\programming\dspace-angular\dist\server\index.js:32:28322)
    at t.configureRequest (D:\programming\dspace-angular\dist\server\index.js:16:2330)
    at t.createConnection (D:\programming\dspace-angular\dist\server\index.js:16:2574)
    at r (D:\programming\dspace-angular\dist\server\index.js:16:2815)
    at t.request (D:\programming\dspace-angular\dist\server\index.js:16:3718)
    at t.get (D:\programming\dspace-angular\dist\server\index.js:16:3789)
    at t.getTranslation (D:\programming\dspace-angular\dist\server\index.js:4:6657)
    at t.getTranslation (D:\programming\dspace-angular\dist\server\index.js:4:7496)
    at t.use (D:\programming\dspace-angular\dist\server\index.js:4:7207)
Error: This method is not implemented in Parse5DomAdapter: getCookie
    at r (D:\programming\dspace-angular\dist\server\index.js:32:15014)
    at e.getCookie (D:\programming\dspace-angular\dist\server\index.js:32:28322)
    at t.configureRequest (D:\programming\dspace-angular\dist\server\index.js:16:2330)
    at t.createConnection (D:\programming\dspace-angular\dist\server\index.js:16:2574)
    at r (D:\programming\dspace-angular\dist\server\index.js:16:2815)
    at t.request (D:\programming\dspace-angular\dist\server\index.js:16:3718)
    at t.get (D:\programming\dspace-angular\dist\server\index.js:16:3789)
    at t.getTranslation (D:\programming\dspace-angular\dist\server\index.js:4:6657)
    at t.getTranslation (D:\programming\dspace-angular\dist\server\index.js:4:7496)
    at t.use (D:\programming\dspace-angular\dist\server\index.js:4:7207)
```
This new error seems to be detailed here: https://github.com/angular/universal-starter/issues/167 and the suggestion in that ticket is the list `UniversalModule` *last* (which is the opposite of the previous suggestion which said it needs to be listed before `TranslateModule`).

**Comment by wwelling** [comment]
I was not able to reproduce on Windows 10.

```
C:\Users\William\work\dspace-angular>yarn -v
yarn install v0.21.3
warning dspace-angular@0.0.0: No license field
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.03s.

C:\Users\William\work\dspace-angular>node -v
v7.5.0

C:\Users\William\work\dspace-angular>npm -v
4.0.2
```

```
npm run global
yarn install
yarn start
```


I do get the following warnings though:

```
Use of `eval` (in C:\Users\William\work\dspace-angular\dist\server\index.js) is strongly discouraged, as it poses security risks and may cause issues with minification. See https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval for more details
Use of `eval` (in C:\Users\William\work\dspace-angular\dist\client\main.bundle.js) is strongly discouraged, as it poses security risks and may cause issues with minification. See https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval for more details
```

**Comment by tdonohue** [comment]
Yes, I saw those `eval` warnings too. I'll give this a test again today (maybe even on my windows laptop). It's possible something is up with my environment. 

Thanks @wwelling for the double check. Hopefully it's just me!

**Comment by tdonohue** [comment]
Closing this as unreproducible. I'm not sure what happened in my environment yesterday, but today I went through the same process:

* `yarn run global`
* `yarn install`
* `yarn start`
* Access http://localhost:3000/

It all worked fine.  I did still see those previously mentioned `eval` warnings still...but I'll log those in a separate ticket.
